//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Base.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDataPermit
    {
        public System.Guid ID { get; set; }
        public System.Guid RoleId { get; set; }
        public Nullable<int> Index { get; set; }
        public System.Guid DataId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Model { get; set; }
        public string Permit { get; set; }
    }
}
