//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Base.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Code_Record
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public System.Guid SchemeId { get; set; }
        public string RelationChar { get; set; }
        public int SerialNumber { get; set; }
        public Nullable<System.Guid> BusinessId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual SYS_Code_Scheme SYS_Code_Scheme { get; set; }
    }
}
