//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Base.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_RolePerm_Action
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid ActionId { get; set; }
        public int Action { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual SYS_ModuleAction SYS_ModuleAction { get; set; }
        public virtual SYS_Role SYS_Role { get; set; }
        public virtual SYS_User SYS_User { get; set; }
    }
}
