//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Base.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ModuleParam
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public System.Guid ModuleId { get; set; }
        public System.Guid ParamId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<System.Guid> OrgId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Description { get; set; }
    
        public virtual SYS_Module SYS_Module { get; set; }
        public virtual SYS_Organization SYS_Organization { get; set; }
        public virtual SYS_User SYS_User { get; set; }
    }
}
