//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(SYS_ModuleParam))]
    [KnownType(typeof(SYS_User))]
    [KnownType(typeof(SYS_Organization))]
    [KnownType(typeof(SYS_OrgMerger))]
    [KnownType(typeof(SYS_OrgMember))]
    [KnownType(typeof(SYS_Role_Title))]
    [KnownType(typeof(SYS_RolePerm_DataAbs))]
    
    public partial class SYS_Organization
    {
        public SYS_Organization()
        {
            this.SYS_ModuleParam = new HashSet<SYS_ModuleParam>();
            this.SYS_Organization1 = new HashSet<SYS_Organization>();
            this.SYS_OrgMerger = new HashSet<SYS_OrgMerger>();
            this.SYS_OrgMember = new HashSet<SYS_OrgMember>();
            this.SYS_OrgMerger1 = new HashSet<SYS_OrgMerger>();
            this.SYS_Role_Title = new HashSet<SYS_Role_Title>();
            this.SYS_RolePerm_DataAbs = new HashSet<SYS_RolePerm_DataAbs>();
        }
    
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Nullable<System.Guid> ParentId { get; set; }
    	[DataMember]
        public int NodeType { get; set; }
    	[DataMember]
        public int Index { get; set; }
    	[DataMember]
        public string Code { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Alias { get; set; }
    	[DataMember]
        public string FullName { get; set; }
    	[DataMember]
        public Nullable<System.Guid> PositionId { get; set; }
    	[DataMember]
        public bool Validity { get; set; }
    	[DataMember]
        public System.Guid CreatorUserId { get; set; }
    	[DataMember]
        public System.DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual ICollection<SYS_ModuleParam> SYS_ModuleParam { get; set; }
    	[DataMember]
        public virtual SYS_User SYS_User { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Organization> SYS_Organization1 { get; set; }
    	[DataMember]
        public virtual SYS_Organization SYS_Organization2 { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_OrgMerger> SYS_OrgMerger { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_OrgMember> SYS_OrgMember { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_OrgMerger> SYS_OrgMerger1 { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Role_Title> SYS_Role_Title { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_RolePerm_DataAbs> SYS_RolePerm_DataAbs { get; set; }
    }
}
