//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(SYS_Module))]
    [KnownType(typeof(SYS_RolePerm_Action))]
    
    public partial class SYS_ModuleAction
    {
        public SYS_ModuleAction()
        {
            this.SYS_RolePerm_Action = new HashSet<SYS_RolePerm_Action>();
        }
    
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public System.Guid ModuleId { get; set; }
    	[DataMember]
        public Nullable<int> Index { get; set; }
    	[DataMember]
        public bool BeginGroup { get; set; }
    	[DataMember]
        public bool ShowText { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Alias { get; set; }
    	[DataMember]
        public Nullable<System.Guid> EntryId { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public bool Validity { get; set; }
    	[DataMember]
        public byte[] Icon { get; set; }
    
    	[DataMember]
        public virtual SYS_Module SYS_Module { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_RolePerm_Action> SYS_RolePerm_Action { get; set; }
    }
}
