//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(SYS_ModuleParam))]
    [KnownType(typeof(SYS_Organization))]
    [KnownType(typeof(SYS_OrgMember))]
    [KnownType(typeof(SYS_OrgMerger))]
    [KnownType(typeof(SYS_Role))]
    [KnownType(typeof(SYS_Role_Title))]
    [KnownType(typeof(SYS_Role_User))]
    [KnownType(typeof(SYS_Role_UserGroup))]
    [KnownType(typeof(SYS_RolePerm_Action))]
    [KnownType(typeof(SYS_RolePerm_Data))]
    [KnownType(typeof(SYS_RolePerm_DataAbs))]
    [KnownType(typeof(SYS_UserGroup))]
    [KnownType(typeof(SYS_UserGroupMember))]
    
    public partial class SYS_User
    {
        public SYS_User()
        {
            this.SYS_ModuleParam = new HashSet<SYS_ModuleParam>();
            this.SYS_Organization = new HashSet<SYS_Organization>();
            this.SYS_OrgMember = new HashSet<SYS_OrgMember>();
            this.SYS_OrgMember1 = new HashSet<SYS_OrgMember>();
            this.SYS_OrgMerger = new HashSet<SYS_OrgMerger>();
            this.SYS_Role = new HashSet<SYS_Role>();
            this.SYS_Role_Title = new HashSet<SYS_Role_Title>();
            this.SYS_Role_User = new HashSet<SYS_Role_User>();
            this.SYS_Role_User1 = new HashSet<SYS_Role_User>();
            this.SYS_Role_UserGroup = new HashSet<SYS_Role_UserGroup>();
            this.SYS_RolePerm_Action = new HashSet<SYS_RolePerm_Action>();
            this.SYS_RolePerm_Data = new HashSet<SYS_RolePerm_Data>();
            this.SYS_RolePerm_DataAbs = new HashSet<SYS_RolePerm_DataAbs>();
            this.SYS_UserGroup = new HashSet<SYS_UserGroup>();
            this.SYS_UserGroupMember = new HashSet<SYS_UserGroupMember>();
            this.SYS_UserGroupMember1 = new HashSet<SYS_UserGroupMember>();
        }
    
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string LoginName { get; set; }
    	[DataMember]
        public string Password { get; set; }
    	[DataMember]
        public string PayPassword { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public int Type { get; set; }
    	[DataMember]
        public bool BuiltIn { get; set; }
    	[DataMember]
        public bool Validity { get; set; }
    	[DataMember]
        public Nullable<System.Guid> CreatorUserId { get; set; }
    	[DataMember]
        public System.DateTime CreateTime { get; set; }
    	[DataMember]
        public string OpenId { get; set; }
    
    	[DataMember]
        public virtual ICollection<SYS_ModuleParam> SYS_ModuleParam { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Organization> SYS_Organization { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_OrgMember> SYS_OrgMember { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_OrgMember> SYS_OrgMember1 { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_OrgMerger> SYS_OrgMerger { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Role> SYS_Role { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Role_Title> SYS_Role_Title { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Role_User> SYS_Role_User { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Role_User> SYS_Role_User1 { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Role_UserGroup> SYS_Role_UserGroup { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_RolePerm_Action> SYS_RolePerm_Action { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_RolePerm_Data> SYS_RolePerm_Data { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_RolePerm_DataAbs> SYS_RolePerm_DataAbs { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_UserGroup> SYS_UserGroup { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_UserGroupMember> SYS_UserGroupMember { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_UserGroupMember> SYS_UserGroupMember1 { get; set; }
    }
}
