//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(SYS_Role_User))]
    [KnownType(typeof(SYS_Role_UserGroup))]
    [KnownType(typeof(SYS_Role_Title))]
    [KnownType(typeof(SYS_User))]
    [KnownType(typeof(SYS_RolePerm_Data))]
    [KnownType(typeof(SYS_RolePerm_DataAbs))]
    [KnownType(typeof(SYS_RolePerm_Action))]
    
    public partial class SYS_Role
    {
        public SYS_Role()
        {
            this.SYS_Role_User = new HashSet<SYS_Role_User>();
            this.SYS_Role_UserGroup = new HashSet<SYS_Role_UserGroup>();
            this.SYS_Role_Title = new HashSet<SYS_Role_Title>();
            this.SYS_RolePerm_Data = new HashSet<SYS_RolePerm_Data>();
            this.SYS_RolePerm_DataAbs = new HashSet<SYS_RolePerm_DataAbs>();
            this.SYS_RolePerm_Action = new HashSet<SYS_RolePerm_Action>();
        }
    
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public bool BuiltIn { get; set; }
    	[DataMember]
        public bool Validity { get; set; }
    	[DataMember]
        public System.Guid CreatorUserId { get; set; }
    	[DataMember]
        public System.DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual ICollection<SYS_Role_User> SYS_Role_User { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Role_UserGroup> SYS_Role_UserGroup { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Role_Title> SYS_Role_Title { get; set; }
    	[DataMember]
        public virtual SYS_User SYS_User { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_RolePerm_Data> SYS_RolePerm_Data { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_RolePerm_DataAbs> SYS_RolePerm_DataAbs { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_RolePerm_Action> SYS_RolePerm_Action { get; set; }
    }
}
