//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Base.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_Module()
        {
            this.SYS_ModuleAction = new HashSet<SYS_ModuleAction>();
            this.SYS_ModuleParam = new HashSet<SYS_ModuleParam>();
            this.SYS_RolePerm_Data = new HashSet<SYS_RolePerm_Data>();
            this.SYS_RolePerm_DataAbs = new HashSet<SYS_RolePerm_DataAbs>();
            this.SYS_Allot_Record = new HashSet<SYS_Allot_Record>();
            this.SYS_Code_Allot = new HashSet<SYS_Code_Allot>();
        }
    
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public Nullable<System.Guid> ModuleGroupId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public int Level { get; set; }
        public int Type { get; set; }
        public Nullable<int> Index { get; set; }
        public string Name { get; set; }
        public string ProgramName { get; set; }
        public string MainFrom { get; set; }
        public string ApplicationName { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public bool Default { get; set; }
        public bool Validity { get; set; }
        public byte[] Icon { get; set; }
    
        public virtual SYS_ModuleGroup SYS_ModuleGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_ModuleAction> SYS_ModuleAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_ModuleParam> SYS_ModuleParam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_RolePerm_Data> SYS_RolePerm_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_RolePerm_DataAbs> SYS_RolePerm_DataAbs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Allot_Record> SYS_Allot_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Code_Allot> SYS_Code_Allot { get; set; }
    }
}
